[project]
name = "fastapiproject1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "requests>=2.32.3",
    "starlette>=0.46.2",
    "structlog>=25.2.0",
    "uvicorn>=0.34.1",
]
